CREATE TABLE whatsforlunch_polls (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  poll_name TEXT,
  end_time TIMESTAMPTZ NOT NULL,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id INTEGER
    REFERENCES whatsforlunch_users(id) ON DELETE CASCADE
);

CREATE TABLE whatsforlunch_poll_items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_name TEXT NOT NULL,
  item_address TEXT,
  item_cuisine TEXT,
  item_link TEXT,
  item_votes INTEGER DEFAULT 0 NOT NULL,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  poll_id INTEGER
    REFERENCES whatsforlunch_polls(id) ON DELETE CASCADE NOT NULL
);
